### ISSUE TITLE
NASAHW1

### ISSUE THREAD

**Issue by Xiphity** [ktpss95112/simple-command-line-game-in-golang#1]
原來在server裡面grep到的repo不是假的嗎XD

**Comment by ktpss95112** [comment]
嗯…當初 release 的時候是用 linux 上的 strip 指令來試圖把一些資訊丟掉，但結果後來發現好像也沒丟乾淨QQ
後來才發現是在 go build 漏加了 -trimpath 參數，加了之後應該就看不到那些資訊了吧？
